language: c
cache:
  directories:
    - $HOME/cachedir
    - $HOME/.ccache
    - $HOME/autom4te.cache
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - MAKEFLAGS="-j5 -rR"
    - EIO_MONITOR_POLL=1
    - CC="ccache gcc"
    - CXX="ccache g++"
  matrix:
    -
    - DISTRO=Ubuntu1804
    - DISTRO=Fedora28 CI_BUILD_TYPE=wayland
    - DISTRO=Fedora28 CI_BUILD_TYPE=misc
    - DISTRO=Fedora28 CI_BUILD_TYPE=misc-disabled
    - DISTRO=Fedora28 CI_BUILD_TYPE=release-ready
    - DISTRO=Debian91
    - DISTRO=Archlinux

services:
  - docker

matrix:
  fast_finish: true
  exclude:
    - os: osx
      env:
        DISTRO=Ubuntu1804
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=wayland
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=misc
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=misc-disabled
    - os: osx
      env:
        DISTRO=Fedora28
        CI_BUILD_TYPE=release-ready
    - os: osx
      env:
        DISTRO=Debian91
    - os: osx
      env:
        DISTRO=Archlinux

    - os: linux
      env:

before_install:
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        rm -rf $HOME/Library/Caches/Homebrew
        rm -rf $HOME/cachedir/Homebrew/Homebrew
        mv $HOME/cachedir/Homebrew $HOME/Library/Caches/Homebrew
        .ci/ci-osx-deps.sh
      elif [[ "$CI_BUILD_TYPE" = "release-ready" ]] ; then
        .ci/distcheck-eval.sh || export DISTCHECK_SKIPPED=1
      fi

before_script:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]] && [[ -z "$DISTCHECK_SKIPPED" ]] ; then
        docker pull stefanschmidt1/ci-support-files:$DISTRO
      fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ -z "$DISTCHECK_SKIPPED" ]] ; then
        docker version
        docker run --cidfile $HOME/cid -t -d -v `pwd`:/src -v $HOME/.ccache:/root/.ccache -w /src stefanschmidt1/ci-support-files:$DISTRO bash
        cp $HOME/cachedir/config.cache . || true
      fi

  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-ccache-stats.sh ; fi
  - |
       if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ -z "$DISTCHECK_SKIPPED" ]] ; then
         cp $HOME/cachedir/config.cache . || true
       fi


script:
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-configure.sh "$CI_BUILD_TYPE" ; fi
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-setup-ccache.sh "$CI_BUILD_TYPE" ; fi
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make.sh "$CI_BUILD_TYPE" ; fi
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make-checkbuild.sh "$CI_BUILD_TYPE" ; fi
  #- if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make-examples.sh "$CI_BUILD_TYPE" ; fi
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$CI_BUILD_TYPE" == "" ]]; then
          .ci/ci-make-benchmark.sh "$CI_BUILD_TYPE"
      fi
  #- if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make-install.sh "$CI_BUILD_TYPE" ; fi
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make-check.sh "$CI_BUILD_TYPE" ; fi
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-make-distcheck.sh "$CI_BUILD_TYPE" ; fi
  #- |
      #if [[ "$DISTRO" == "" ]] && [[ "$TRAVIS_OS_NAME" != "linux" ]] ; then
        #true
      #elif [[ "$CI_BUILD_TYPE" != "release-ready" ]] ; then
        #docker exec --env MAKEFLAGS="-j5 -rR" --env EIO_MONITOR_POLL=1 $(cat $HOME/cid) .ci/build-efl-app.sh
      #fi
before_cache:
  - if [[ -z "$DISTCHECK_SKIPPED" ]] ; then .ci/ci-ccache-stats.sh ; fi
  - |
       mkdir -p $HOME/cachedir
       if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ -z "$DISTCHECK_SKIPPED" ]] ; then
         sudo chown travis:travis $HOME/.ccache
         mkdir -p $HOME/cachedir/
         sudo cp config.cache $HOME/cachedir/
         sudo chown travis:travis $HOME/cachedir/config.cache
         sudo chown travis:travis $HOME/autom4te.cache
       else
         cp config.cache $HOME/cachedir
         mv $HOME/Library/Caches/Homebrew $HOME/cachedir/Homebrew
       fi

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]] && [[ -z "$DISTCHECK_SKIPPED" ]]; then
        docker login -u stefanschmidt1 -p "$DOCKER_PASSWORD"
        docker tag stefanschmidt1/ci-support-files:$DISTRO stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
        docker push stefanschmidt1/ci-support-files:$DISTRO
        docker push stefanschmidt1/ci-support-files:$DISTRO-$TRAVIS_BUILD_NUMBER
      fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#edevelop"
    on_success: change
    on_failure: always
    on_cancel: never
    template:
      - "TravisCI build %{build_number} in branch %{branch}: %{result} - %{message} (%{elapsed_time})"
      - "Commit: %{commit_subject} (%{commit}) from %{author}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
